// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: civilizations.sql

package dbgen

import (
	"context"
)

const countQuotesByCiv = `-- name: CountQuotesByCiv :one
SELECT COUNT(*) as count FROM quotes WHERE civilization = ?
`

func (q *Queries) CountQuotesByCiv(ctx context.Context, civilization *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuotesByCiv, civilization)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCiv = `-- name: CreateCiv :exec
INSERT INTO civilizations (name, variant_of, dlc) VALUES (?, ?, ?)
`

type CreateCivParams struct {
	Name      string  `json:"name"`
	VariantOf *string `json:"variant_of"`
	Dlc       *string `json:"dlc"`
}

func (q *Queries) CreateCiv(ctx context.Context, arg CreateCivParams) error {
	_, err := q.db.ExecContext(ctx, createCiv, arg.Name, arg.VariantOf, arg.Dlc)
	return err
}

const deleteCiv = `-- name: DeleteCiv :exec
DELETE FROM civilizations WHERE id = ?
`

func (q *Queries) DeleteCiv(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCiv, id)
	return err
}

const getCivByID = `-- name: GetCivByID :one
SELECT id, name, variant_of, dlc, created_at FROM civilizations WHERE id = ?
`

func (q *Queries) GetCivByID(ctx context.Context, id int64) (Civilization, error) {
	row := q.db.QueryRowContext(ctx, getCivByID, id)
	var i Civilization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VariantOf,
		&i.Dlc,
		&i.CreatedAt,
	)
	return i, err
}

const getCivByName = `-- name: GetCivByName :one
SELECT id, name, variant_of, dlc, created_at FROM civilizations WHERE name = ?
`

func (q *Queries) GetCivByName(ctx context.Context, name string) (Civilization, error) {
	row := q.db.QueryRowContext(ctx, getCivByName, name)
	var i Civilization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VariantOf,
		&i.Dlc,
		&i.CreatedAt,
	)
	return i, err
}

const listCivs = `-- name: ListCivs :many
SELECT id, name, variant_of, dlc, created_at FROM civilizations ORDER BY name
`

func (q *Queries) ListCivs(ctx context.Context) ([]Civilization, error) {
	rows, err := q.db.QueryContext(ctx, listCivs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Civilization{}
	for rows.Next() {
		var i Civilization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VariantOf,
			&i.Dlc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCiv = `-- name: UpdateCiv :exec
UPDATE civilizations SET name = ?, variant_of = ?, dlc = ? WHERE id = ?
`

type UpdateCivParams struct {
	Name      string  `json:"name"`
	VariantOf *string `json:"variant_of"`
	Dlc       *string `json:"dlc"`
	ID        int64   `json:"id"`
}

func (q *Queries) UpdateCiv(ctx context.Context, arg UpdateCivParams) error {
	_, err := q.db.ExecContext(ctx, updateCiv,
		arg.Name,
		arg.VariantOf,
		arg.Dlc,
		arg.ID,
	)
	return err
}
