// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: civilizations.sql

package dbgen

import (
	"context"
)

const countQuotesByCiv = `-- name: CountQuotesByCiv :one
SELECT COUNT(*) as count FROM quotes WHERE civilization = ?
`

func (q *Queries) CountQuotesByCiv(ctx context.Context, civilization *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuotesByCiv, civilization)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCivByName = `-- name: GetCivByName :one
SELECT id, name, variant_of, dlc, created_at FROM civilizations WHERE name = ?
`

func (q *Queries) GetCivByName(ctx context.Context, name string) (Civilization, error) {
	row := q.db.QueryRowContext(ctx, getCivByName, name)
	var i Civilization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VariantOf,
		&i.Dlc,
		&i.CreatedAt,
	)
	return i, err
}

const listCivs = `-- name: ListCivs :many
SELECT id, name, variant_of, dlc, created_at FROM civilizations ORDER BY name
`

func (q *Queries) ListCivs(ctx context.Context) ([]Civilization, error) {
	rows, err := q.db.QueryContext(ctx, listCivs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Civilization{}
	for rows.Next() {
		var i Civilization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VariantOf,
			&i.Dlc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
