// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: managed_channels.sql

package dbgen

import (
	"context"
)

const createManagedChannel = `-- name: CreateManagedChannel :one

INSERT INTO nightbot_managed_channels (
    user_email, channel_id, channel_name, session_token_encrypted,
    sync_enabled, sync_interval_minutes
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateManagedChannelParams struct {
	UserEmail             string `json:"user_email"`
	ChannelID             string `json:"channel_id"`
	ChannelName           string `json:"channel_name"`
	SessionTokenEncrypted string `json:"session_token_encrypted"`
	SyncEnabled           int64  `json:"sync_enabled"`
	SyncIntervalMinutes   int64  `json:"sync_interval_minutes"`
}

// Managed channels queries for automated Nightbot backup
func (q *Queries) CreateManagedChannel(ctx context.Context, arg CreateManagedChannelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createManagedChannel,
		arg.UserEmail,
		arg.ChannelID,
		arg.ChannelName,
		arg.SessionTokenEncrypted,
		arg.SyncEnabled,
		arg.SyncIntervalMinutes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteManagedChannel = `-- name: DeleteManagedChannel :exec
DELETE FROM nightbot_managed_channels WHERE id = ?
`

func (q *Queries) DeleteManagedChannel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteManagedChannel, id)
	return err
}

const disableManagedChannelSync = `-- name: DisableManagedChannelSync :exec
UPDATE nightbot_managed_channels
SET sync_enabled = 0,
    last_sync_status = 'disabled',
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) DisableManagedChannelSync(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, disableManagedChannelSync, id)
	return err
}

const enableManagedChannelSync = `-- name: EnableManagedChannelSync :exec
UPDATE nightbot_managed_channels
SET sync_enabled = 1,
    last_sync_status = NULL,
    last_error = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) EnableManagedChannelSync(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, enableManagedChannelSync, id)
	return err
}

const getAllManagedChannels = `-- name: GetAllManagedChannels :many
SELECT id, user_email, channel_id, channel_name, session_token_encrypted, sync_enabled, sync_interval_minutes, last_sync_at, last_sync_status, last_error, created_at, updated_at FROM nightbot_managed_channels ORDER BY channel_name
`

func (q *Queries) GetAllManagedChannels(ctx context.Context) ([]NightbotManagedChannel, error) {
	rows, err := q.db.QueryContext(ctx, getAllManagedChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NightbotManagedChannel{}
	for rows.Next() {
		var i NightbotManagedChannel
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.ChannelID,
			&i.ChannelName,
			&i.SessionTokenEncrypted,
			&i.SyncEnabled,
			&i.SyncIntervalMinutes,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManagedChannel = `-- name: GetManagedChannel :one
SELECT id, user_email, channel_id, channel_name, session_token_encrypted, sync_enabled, sync_interval_minutes, last_sync_at, last_sync_status, last_error, created_at, updated_at FROM nightbot_managed_channels WHERE id = ?
`

func (q *Queries) GetManagedChannel(ctx context.Context, id int64) (NightbotManagedChannel, error) {
	row := q.db.QueryRowContext(ctx, getManagedChannel, id)
	var i NightbotManagedChannel
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.ChannelID,
		&i.ChannelName,
		&i.SessionTokenEncrypted,
		&i.SyncEnabled,
		&i.SyncIntervalMinutes,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedChannelByChannelID = `-- name: GetManagedChannelByChannelID :one
SELECT id, user_email, channel_id, channel_name, session_token_encrypted, sync_enabled, sync_interval_minutes, last_sync_at, last_sync_status, last_error, created_at, updated_at FROM nightbot_managed_channels WHERE channel_id = ?
`

func (q *Queries) GetManagedChannelByChannelID(ctx context.Context, channelID string) (NightbotManagedChannel, error) {
	row := q.db.QueryRowContext(ctx, getManagedChannelByChannelID, channelID)
	var i NightbotManagedChannel
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.ChannelID,
		&i.ChannelName,
		&i.SessionTokenEncrypted,
		&i.SyncEnabled,
		&i.SyncIntervalMinutes,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedChannelsByUser = `-- name: GetManagedChannelsByUser :many
SELECT id, user_email, channel_id, channel_name, session_token_encrypted, sync_enabled, sync_interval_minutes, last_sync_at, last_sync_status, last_error, created_at, updated_at FROM nightbot_managed_channels WHERE user_email = ? ORDER BY channel_name
`

func (q *Queries) GetManagedChannelsByUser(ctx context.Context, userEmail string) ([]NightbotManagedChannel, error) {
	rows, err := q.db.QueryContext(ctx, getManagedChannelsByUser, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NightbotManagedChannel{}
	for rows.Next() {
		var i NightbotManagedChannel
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.ChannelID,
			&i.ChannelName,
			&i.SessionTokenEncrypted,
			&i.SyncEnabled,
			&i.SyncIntervalMinutes,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManagedChannelsDueForSync = `-- name: GetManagedChannelsDueForSync :many
SELECT id, user_email, channel_id, channel_name, session_token_encrypted, sync_enabled, sync_interval_minutes, last_sync_at, last_sync_status, last_error, created_at, updated_at FROM nightbot_managed_channels
WHERE sync_enabled = 1
  AND (last_sync_at IS NULL 
       OR datetime(last_sync_at, '+' || sync_interval_minutes || ' minutes') <= datetime('now'))
ORDER BY last_sync_at ASC NULLS FIRST
`

// Returns channels that are enabled and due for sync based on their interval
func (q *Queries) GetManagedChannelsDueForSync(ctx context.Context) ([]NightbotManagedChannel, error) {
	rows, err := q.db.QueryContext(ctx, getManagedChannelsDueForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NightbotManagedChannel{}
	for rows.Next() {
		var i NightbotManagedChannel
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.ChannelID,
			&i.ChannelName,
			&i.SessionTokenEncrypted,
			&i.SyncEnabled,
			&i.SyncIntervalMinutes,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManagedChannelSettings = `-- name: UpdateManagedChannelSettings :exec
UPDATE nightbot_managed_channels
SET channel_name = ?,
    sync_enabled = ?,
    sync_interval_minutes = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateManagedChannelSettingsParams struct {
	ChannelName         string `json:"channel_name"`
	SyncEnabled         int64  `json:"sync_enabled"`
	SyncIntervalMinutes int64  `json:"sync_interval_minutes"`
	ID                  int64  `json:"id"`
}

func (q *Queries) UpdateManagedChannelSettings(ctx context.Context, arg UpdateManagedChannelSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateManagedChannelSettings,
		arg.ChannelName,
		arg.SyncEnabled,
		arg.SyncIntervalMinutes,
		arg.ID,
	)
	return err
}

const updateManagedChannelSyncStatus = `-- name: UpdateManagedChannelSyncStatus :exec
UPDATE nightbot_managed_channels
SET last_sync_at = CURRENT_TIMESTAMP,
    last_sync_status = ?,
    last_error = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateManagedChannelSyncStatusParams struct {
	LastSyncStatus *string `json:"last_sync_status"`
	LastError      *string `json:"last_error"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateManagedChannelSyncStatus(ctx context.Context, arg UpdateManagedChannelSyncStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateManagedChannelSyncStatus, arg.LastSyncStatus, arg.LastError, arg.ID)
	return err
}

const updateManagedChannelToken = `-- name: UpdateManagedChannelToken :exec
UPDATE nightbot_managed_channels
SET session_token_encrypted = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateManagedChannelTokenParams struct {
	SessionTokenEncrypted string `json:"session_token_encrypted"`
	ID                    int64  `json:"id"`
}

func (q *Queries) UpdateManagedChannelToken(ctx context.Context, arg UpdateManagedChannelTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateManagedChannelToken, arg.SessionTokenEncrypted, arg.ID)
	return err
}
