// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Civilization struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	VariantOf *string   `json:"variant_of"`
	Dlc       *string   `json:"dlc"`
	CreatedAt time.Time `json:"created_at"`
	Shortname *string   `json:"shortname"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Quote struct {
	ID           int64     `json:"id"`
	UserID       string    `json:"user_id"`
	Text         string    `json:"text"`
	Author       *string   `json:"author"`
	CreatedAt    time.Time `json:"created_at"`
	Civilization *string   `json:"civilization"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
