// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type ChannelOwner struct {
	ID        int64     `json:"id"`
	Channel   string    `json:"channel"`
	UserEmail string    `json:"user_email"`
	InvitedAt time.Time `json:"invited_at"`
	InvitedBy string    `json:"invited_by"`
}

type Civilization struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	VariantOf *string   `json:"variant_of"`
	Dlc       *string   `json:"dlc"`
	CreatedAt time.Time `json:"created_at"`
	Shortname *string   `json:"shortname"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type NightbotSnapshot struct {
	ID           int64     `json:"id"`
	ChannelName  string    `json:"channel_name"`
	SnapshotAt   time.Time `json:"snapshot_at"`
	CommandCount int64     `json:"command_count"`
	CommandsJson string    `json:"commands_json"`
	CreatedBy    string    `json:"created_by"`
	Note         *string   `json:"note"`
}

type NightbotToken struct {
	ID                 int64     `json:"id"`
	UserEmail          string    `json:"user_email"`
	ChannelName        string    `json:"channel_name"`
	ChannelDisplayName *string   `json:"channel_display_name"`
	AccessToken        string    `json:"access_token"`
	RefreshToken       string    `json:"refresh_token"`
	ExpiresAt          time.Time `json:"expires_at"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type Quote struct {
	ID             int64     `json:"id"`
	UserID         string    `json:"user_id"`
	Text           string    `json:"text"`
	Author         *string   `json:"author"`
	CreatedAt      time.Time `json:"created_at"`
	Civilization   *string   `json:"civilization"`
	OpponentCiv    *string   `json:"opponent_civ"`
	Channel        *string   `json:"channel"`
	CreatedByEmail *string   `json:"created_by_email"`
	RequestedBy    *string   `json:"requested_by"`
}

type QuoteSuggestion struct {
	ID              int64      `json:"id"`
	Text            string     `json:"text"`
	Author          *string    `json:"author"`
	Civilization    *string    `json:"civilization"`
	OpponentCiv     *string    `json:"opponent_civ"`
	Channel         string     `json:"channel"`
	SubmittedByIp   string     `json:"submitted_by_ip"`
	SubmittedAt     time.Time  `json:"submitted_at"`
	Status          string     `json:"status"`
	ReviewedBy      *string    `json:"reviewed_by"`
	ReviewedAt      *time.Time `json:"reviewed_at"`
	SubmittedByUser *string    `json:"submitted_by_user"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
