// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nightbot_moderators.sql

package dbgen

import (
	"context"
)

const addChannelModerator = `-- name: AddChannelModerator :exec

INSERT INTO nightbot_channel_moderators (channel_name, user_email, added_by)
VALUES (?, ?, ?)
ON CONFLICT (channel_name, user_email) DO NOTHING
`

type AddChannelModeratorParams struct {
	ChannelName string `json:"channel_name"`
	UserEmail   string `json:"user_email"`
	AddedBy     string `json:"added_by"`
}

// Nightbot channel moderator queries
func (q *Queries) AddChannelModerator(ctx context.Context, arg AddChannelModeratorParams) error {
	_, err := q.db.ExecContext(ctx, addChannelModerator, arg.ChannelName, arg.UserEmail, arg.AddedBy)
	return err
}

const getAllModerators = `-- name: GetAllModerators :many
SELECT id, channel_name, user_email, added_by, added_at FROM nightbot_channel_moderators ORDER BY channel_name, user_email
`

func (q *Queries) GetAllModerators(ctx context.Context) ([]NightbotChannelModerator, error) {
	rows, err := q.db.QueryContext(ctx, getAllModerators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NightbotChannelModerator{}
	for rows.Next() {
		var i NightbotChannelModerator
		if err := rows.Scan(
			&i.ID,
			&i.ChannelName,
			&i.UserEmail,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllModeratorsByChannel = `-- name: GetAllModeratorsByChannel :many
SELECT channel_name, GROUP_CONCAT(user_email) as emails
FROM nightbot_channel_moderators 
GROUP BY channel_name 
ORDER BY channel_name
`

type GetAllModeratorsByChannelRow struct {
	ChannelName string `json:"channel_name"`
	Emails      string `json:"emails"`
}

func (q *Queries) GetAllModeratorsByChannel(ctx context.Context) ([]GetAllModeratorsByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllModeratorsByChannel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllModeratorsByChannelRow{}
	for rows.Next() {
		var i GetAllModeratorsByChannelRow
		if err := rows.Scan(&i.ChannelName, &i.Emails); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelModerators = `-- name: GetChannelModerators :many
SELECT id, channel_name, user_email, added_by, added_at FROM nightbot_channel_moderators WHERE channel_name = ? ORDER BY added_at
`

func (q *Queries) GetChannelModerators(ctx context.Context, channelName string) ([]NightbotChannelModerator, error) {
	rows, err := q.db.QueryContext(ctx, getChannelModerators, channelName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NightbotChannelModerator{}
	for rows.Next() {
		var i NightbotChannelModerator
		if err := rows.Scan(
			&i.ID,
			&i.ChannelName,
			&i.UserEmail,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModeratorChannels = `-- name: GetModeratorChannels :many
SELECT DISTINCT channel_name FROM nightbot_channel_moderators WHERE user_email = ? ORDER BY channel_name
`

// Returns channels a user can moderate
func (q *Queries) GetModeratorChannels(ctx context.Context, userEmail string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getModeratorChannels, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var channel_name string
		if err := rows.Scan(&channel_name); err != nil {
			return nil, err
		}
		items = append(items, channel_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChannelModerator = `-- name: IsChannelModerator :one
SELECT COUNT(*) > 0 as is_moderator FROM nightbot_channel_moderators 
WHERE channel_name = ? AND user_email = ?
`

type IsChannelModeratorParams struct {
	ChannelName string `json:"channel_name"`
	UserEmail   string `json:"user_email"`
}

func (q *Queries) IsChannelModerator(ctx context.Context, arg IsChannelModeratorParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isChannelModerator, arg.ChannelName, arg.UserEmail)
	var is_moderator bool
	err := row.Scan(&is_moderator)
	return is_moderator, err
}

const removeChannelModerator = `-- name: RemoveChannelModerator :exec
DELETE FROM nightbot_channel_moderators WHERE id = ?
`

func (q *Queries) RemoveChannelModerator(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeChannelModerator, id)
	return err
}
