// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: twitch_auth.sql

package dbgen

import (
	"context"
	"time"
)

const createTwitchSession = `-- name: CreateTwitchSession :exec

INSERT INTO twitch_sessions (id, twitch_id, twitch_username, display_name, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateTwitchSessionParams struct {
	ID             string    `json:"id"`
	TwitchID       string    `json:"twitch_id"`
	TwitchUsername string    `json:"twitch_username"`
	DisplayName    *string   `json:"display_name"`
	ExpiresAt      time.Time `json:"expires_at"`
}

// Twitch authentication queries
func (q *Queries) CreateTwitchSession(ctx context.Context, arg CreateTwitchSessionParams) error {
	_, err := q.db.ExecContext(ctx, createTwitchSession,
		arg.ID,
		arg.TwitchID,
		arg.TwitchUsername,
		arg.DisplayName,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredTwitchSessions = `-- name: DeleteExpiredTwitchSessions :exec
DELETE FROM twitch_sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredTwitchSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTwitchSessions)
	return err
}

const deleteTwitchSession = `-- name: DeleteTwitchSession :exec
DELETE FROM twitch_sessions WHERE id = ?
`

func (q *Queries) DeleteTwitchSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTwitchSession, id)
	return err
}

const getModeratorChannelsByTwitch = `-- name: GetModeratorChannelsByTwitch :many
SELECT channel_name FROM nightbot_channel_moderators
WHERE twitch_username = ?
ORDER BY channel_name
`

func (q *Queries) GetModeratorChannelsByTwitch(ctx context.Context, twitchUsername *string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getModeratorChannelsByTwitch, twitchUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var channel_name string
		if err := rows.Scan(&channel_name); err != nil {
			return nil, err
		}
		items = append(items, channel_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTwitchSession = `-- name: GetTwitchSession :one
SELECT id, twitch_id, twitch_username, display_name, created_at, expires_at FROM twitch_sessions WHERE id = ? AND expires_at > datetime('now')
`

func (q *Queries) GetTwitchSession(ctx context.Context, id string) (TwitchSession, error) {
	row := q.db.QueryRowContext(ctx, getTwitchSession, id)
	var i TwitchSession
	err := row.Scan(
		&i.ID,
		&i.TwitchID,
		&i.TwitchUsername,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const isChannelModeratorByTwitch = `-- name: IsChannelModeratorByTwitch :one
SELECT EXISTS(
    SELECT 1 FROM nightbot_channel_moderators
    WHERE channel_name = ? AND twitch_username = ?
) AS is_moderator
`

type IsChannelModeratorByTwitchParams struct {
	ChannelName    string  `json:"channel_name"`
	TwitchUsername *string `json:"twitch_username"`
}

func (q *Queries) IsChannelModeratorByTwitch(ctx context.Context, arg IsChannelModeratorByTwitchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isChannelModeratorByTwitch, arg.ChannelName, arg.TwitchUsername)
	var is_moderator int64
	err := row.Scan(&is_moderator)
	return is_moderator, err
}
