// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
)

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, user_id, email, first_seen_at, last_seen_at, visit_count FROM users ORDER BY last_seen_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.VisitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentUsers = `-- name: GetRecentUsers :many
SELECT id, user_id, email, first_seen_at, last_seen_at, visit_count FROM users ORDER BY last_seen_at DESC LIMIT ?
`

func (q *Queries) GetRecentUsers(ctx context.Context, limit int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getRecentUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.VisitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_id, email, first_seen_at, last_seen_at, visit_count FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.VisitCount,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_id, email, first_seen_at, last_seen_at, visit_count FROM users WHERE user_id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.VisitCount,
	)
	return i, err
}

const getUserCount = `-- name: GetUserCount :one
SELECT COUNT(*) FROM users
`

func (q *Queries) GetUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertUser = `-- name: UpsertUser :exec

INSERT INTO users (user_id, email, first_seen_at, last_seen_at, visit_count)
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1)
ON CONFLICT (user_id) DO UPDATE SET
    email = excluded.email,
    last_seen_at = CURRENT_TIMESTAMP,
    visit_count = visit_count + 1
`

type UpsertUserParams struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
}

// User tracking queries
// Record a user visit (insert or update last_seen and visit_count)
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser, arg.UserID, arg.Email)
	return err
}
