// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visitors.sql

package dbgen

import (
	"context"
	"time"
)

const upsertVisitor = `-- name: UpsertVisitor :exec
INSERT INTO
  visitors (id, view_count, created_at, last_seen)
VALUES
  (?, 1, ?, ?) ON CONFLICT (id) DO
UPDATE
SET
  view_count = view_count + 1,
  last_seen = excluded.last_seen
`

type UpsertVisitorParams struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}

func (q *Queries) UpsertVisitor(ctx context.Context, arg UpsertVisitorParams) error {
	_, err := q.db.ExecContext(ctx, upsertVisitor, arg.ID, arg.CreatedAt, arg.LastSeen)
	return err
}

const visitorWithID = `-- name: VisitorWithID :one
SELECT
  id, view_count, created_at, last_seen
FROM
  visitors
WHERE
  id = ?
`

func (q *Queries) VisitorWithID(ctx context.Context, id string) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, visitorWithID, id)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.ViewCount,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}
